#ifndef PARAMETRISOTTERRANEI_GLOBAL_H
#define PARAMETRISOTTERRANEI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PARAMETRISOTTERRANEI_LIBRARY)
#  define PARAMETRISOTTERRANEISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PARAMETRISOTTERRANEISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PARAMETRISOTTERRANEI_GLOBAL_H
